replicaCount: 1
image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent
  port: 27017

#imagePullSecrets: anuphnu-registry

#resources:
#  limits:
#    cpu: 800m
#    memory: 1000Mi
#  requests:
#    cpu: 800m
#    memory: 1000Mi

service:
  type: ClusterIP
  port: 27017


storage:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
  capacity: 10Gi
